<?php

/**
 * @file
 * Module file for the LocalGov Publications module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\localgov_roles\RolesHelper;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\Role;

/**
 * Implements hook_theme().
 */
function localgov_publications_theme($existing, $type, $theme, $path) {
  return [
    'book_navigation__publication' => [
      'template' => 'book-navigation--publication',
      'base hook' => 'book_navigation__publication',
    ],
    'localgov_publication_page_header_block' => [
      'variables' => [
        'title' => '',
        'node_title' => '',
        'published_date' => NULL,
        'last_updated_date' => NULL,
      ],
    ],
    'paragraph__localgov_publications_banner' => [
      'template' => 'paragraph--localgov-publications-banner',
      'base hook' => 'paragraph',
    ],
    'media__document__publication' => [
      'template' => 'media--document--publication',
      'base hook' => 'media',
    ],
    'field__localgov_publication' => [
      'template' => 'publication-html-reference',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_modules_installed().
 */
function localgov_publications_modules_installed($modules, $is_syncing) {
  if (!$is_syncing && in_array('localgov_publications', $modules)) {
    // Add permission to use the publications text format this module provides.
    $role_object = Role::load('authenticated');
    $role_object->grantPermission('use text format publications');
    $role_object->save();
  }
}

/**
 * Implements hook_localgov_role_default().
 */
function localgov_publications_localgov_roles_default() {
  return [
    RolesHelper::EDITOR_ROLE => [
      'add content to books',
      'administer book outlines',
      'create new books',
      'create localgov_publication_page content',
      'create localgov_publication_cover_page content',
      'delete any localgov_publication_page content',
      'delete any localgov_publication_cover_page content',
      'delete localgov_publication_page revisions',
      'delete localgov_publication_cover_page revisions',
      'delete own localgov_publication_page content',
      'delete own localgov_publication_cover_page content',
      'edit any localgov_publication_page content',
      'edit any localgov_publication_cover_page content',
      'edit own localgov_publication_page content',
      'edit own localgov_publication_cover_page content',
      'revert localgov_publication_page revisions',
      'revert localgov_publication_cover_page revisions',
      'view localgov_publication_page revisions',
      'view localgov_publication_cover_page revisions',
    ],
  ];
}

/**
 * Is the given type one of the publication node types?
 */
function localgov_publications_is_publication_type(string $type): bool {
  return $type === 'localgov_publication_page' || $type === 'localgov_publication_cover_page';
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function localgov_publications_theme_suggestions_book_navigation(array $variables) {
  $suggestions = [];

  // Only add suggestion on publication pages and publication cover pages.
  $node = \Drupal::routeMatch()->getParameter('node');
  if (localgov_publications_is_publication_type($node->getType())) {
    $suggestions[] = $variables['theme_hook_original'] . '__' . 'publication';
  }

  return $suggestions;
}

/**
 * Implements hook_block_access().
 */
function localgov_publications_block_access(Block $block, $operation, AccountInterface $account) {
  if ($block->getPluginId() == 'localgov_page_header_block' && $operation == 'view') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface && localgov_publications_is_publication_type($node->getType())) {
      return AccessResult::forbiddenIf(TRUE)->addCacheableDependency($block);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for book_admin_edit.
 */
function localgov_publications_form_book_admin_edit_alter(&$form, FormStateInterface $form_state, $form_id) {

  // If we're on the route this module uses for this form, change some wording.
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'publication.admin_edit') {
    $form['save']['#value'] = t('Save publication pages');
  }
}

/**
 * Implements hook_form_alter().
 */
function localgov_publications_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $forms_to_alter = [
    'node_localgov_publication_cover_page_form',
    'node_localgov_publication_cover_page_edit_form',
    'node_localgov_publication_page_form',
    'node_localgov_publication_page_edit_form',
  ];

  if (!in_array($form_id, $forms_to_alter)) {
    return;
  }

  // Get the node.
  $node = $form_state->getFormObject()->getEntity();

  // Attach JS.
  if ($form['book']['#attached']['library'][0] == 'book/drupal.book') {
    unset($form['book']['#attached']['library']);
    $form['book']['#attached']['library'][0] = 'localgov_publications/localgov-publications';
  }

  // Get form state values.
  $book_values = $form_state->getValue('book');

  // Alter the book outline form title.
  $form['book']['#title'] = t('Publication outline');

  // Alter the select element.
  $form['book']['bid']['#title'] = t('Publication');

  // Change "Create new book" to "Create a new publication".
  if (!empty($form['book']['bid']['#options']['new'])) {
    $form['book']['bid']['#options']['new'] = t('- Create a new publication -');
  }

  $form['book']['bid']['#description'] = t('Your page will be part of the selected publication');

  // Alter "No book selected".
  if (empty($book_values)) {
    $form['book']['pid']['#prefix'] = '<div id="edit-book-plid-wrapper"><em>No publication selected.</em>';
  }
  else {
    switch ($book_values['bid']) {
      case '0':
        $form['book']['pid']['#prefix'] = '<div id="edit-book-plid-wrapper"><em>No publication selected.</em>';
        break;

      case 'new':
      case $node->id():
        $form['book']['pid']['#prefix'] = '<div id="edit-book-plid-wrapper"><em>This will be the top-level page in this publication.</em>';
        break;

      default:
        $form['book']['pid']['#description'] = t(
          'The parent page in the publication. The maximum depth for a publication and all child pages is @maxdepth. Some pages in the selected publication may not be available as parents if selecting them would exceed this limit.',
          ['@maxdepth' => $form['book']['parent_depth_limit']['#value']],
        );
        break;
    }
  }

  if ($form_id == 'node_localgov_publication_page_form' || $form_id == 'node_localgov_publication_page_edit_form') {
    $form['#validate'][] = 'localgov_publications_validate_node_form';
  }
}

/**
 * Form validation function.
 *
 * Ensures that either 'Create a new publication', or an existing publication
 * has been chosen from the book field.
 */
function localgov_publications_validate_node_form(&$form, FormStateInterface $form_state) {

  if ($form_state->hasValue('book')) {
    $book = $form_state->getValue('book');
    if ($book['bid'] === '0') {
      $form_state->setErrorByName('book', t("Please choose either 'Create a new publication', or one of your existing publications for this page to be part of."));
    }
  }
}

/**
 * Implements hook_node_links_alter().
 *
 * If book module has added the "Add child page" link, and we're on a
 * publication type page, alter the link, so it creates a
 * localgov_publication_page, instead of the default book type.
 */
function localgov_publications_node_links_alter(array &$links, NodeInterface $node, array &$context) {

  if (localgov_publications_is_publication_type($node->getType()) && !empty($links['book']['#links']['book_add_child'])) {
    $links['book']['#links']['book_add_child']['url'] = Url::fromRoute('node.add', ['node_type' => 'localgov_publication_page'], ['query' => ['parent' => $node->id()]]);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function localgov_publications_preprocess_node(&$variables) {
  $view_mode = $variables['elements']['#view_mode'];
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['elements']['#node'];

  if ($view_mode === 'full' && localgov_publications_is_publication_type($node->getType())) {
    $variables['content']['#attached']['library'][] = 'localgov_publications/localgov-publications';
  }
}
