<?php

/**
 * @file
 * Module file for the LocalGov Publications module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\Role;

/**
 * Implements hook_theme().
 */
function localgov_publications_theme($existing, $type, $theme, $path) {
  return [
    'book_navigation__publication' => [
      'template' => 'book-navigation--publication',
      'base hook' => 'book_navigation__publication',
    ],
    'paragraph__localgov_numbered_text' => [
      'template' => 'paragraph--localgov-numbered-text',
      'base hook' => 'paragraph',
    ],
    'localgov_publication_page_header_block' => [
      'variables' => [
        'title' => NULL,
        'published_date' => NULL,
        'last_updated_date' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_install().
 */
function localgov_publications_modules_installed($modules, $is_syncing) {
  if (!$is_syncing && in_array('localgov_publications', $modules)) {
    // Add permission to use the publications text format this module provides.
    $role_object = Role::load('authenticated');
    $role_object->grantPermission('use text format publications');
    $role_object->save();
  }
}

/**
 * Is the given type one of the publication node types?
 */
function localgov_publications_is_publication_type(string $type): bool {
  return $type === 'localgov_publication_page' || $type === 'publication_landing_page';
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function localgov_publications_theme_suggestions_book_navigation(array $variables) {
  $suggestions = [];

  // Only add suggestion on publication pages and publication landing pages.
  $node = \Drupal::routeMatch()->getParameter('node');
  if (localgov_publications_is_publication_type($node->getType())) {
    $original = $variables['theme_hook_original'] . '__';
    $suggestions[] = $original . 'publication';
  }

  return $suggestions;
}

/**
 * Implements hook_block_access().
 */
function localgov_publications_block_access(Block $block, $operation, AccountInterface $account) {
  if ($block->getPluginId() == 'localgov_page_header_block' && $operation == 'view') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if (!empty($node) && $node instanceof NodeInterface && $node->getType() == 'localgov_publication_page') {
      return AccessResult::forbiddenIf(TRUE)->addCacheableDependency($block);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for book_admin_edit.
 */
function localgov_publications_form_book_admin_edit_alter(&$form, FormStateInterface $form_state, $form_id) {

  // If we're on the route this module uses for this form, change some wording.
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'publication.admin_edit') {
    $form['save']['#value'] = t('Save publication pages');
  }
}

/**
 * Implements hook_form_alter().
 */
function localgov_publications_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $forms_to_alter = [
    'node_publication_landing_page_form',
    'node_publication_landing_page_edit_form',
    'node_localgov_publication_page_form',
    'node_localgov_publication_page_edit_form',
  ];

  if (!in_array($form_id, $forms_to_alter)) {
    return;
  }

  // Get the node.
  $node = $form_state->getFormObject()->getEntity();

  // Attach JS.
  if ($form['book']['#attached']['library'][0] == 'book/drupal.book') {
    unset($form['book']['#attached']['library']);
    $form['book']['#attached']['library'][0] = 'localgov_publications/localgov-publications';
  }

  // Get form state values.
  $book_values = $form_state->getValue('book');

  // Alter the book outline form title.
  $form['book']['#title'] = t('Publication outline');

  // Alter the select element.
  $form['book']['bid']['#title'] = t('Publication');

  // Change the "Create new book".
  if (!empty($form['book']['bid']['#options'][$node->id()])) {
    $form['book']['bid']['#options'][$node->id()] = t(
      '- Create a new publication -',
    );
  }
  elseif (!empty($form['book']['bid']['#options']['new'])) {
    $form['book']['bid']['#options']['new'] = t(
      '- Create a new publication -',
    );
  }

  $form['book']['bid']['#description'] = t(
    'Your page will be part of the selected publication',
  );

  // Alter "No book selected".
  if (empty($book_values)) {
    $form['book']['pid']['#prefix'] =
      '<div id="edit-book-plid-wrapper"><em>No publication selected.</em>';
  }
  else {
    switch ($book_values['bid']) {
      case '0':
        $form['book']['pid']['#prefix'] =
          '<div id="edit-book-plid-wrapper"><em>No publication selected.</em>';
        break;

      case 'new':
      case $node->id():
        $form['book']['pid']['#prefix'] =
          '<div id="edit-book-plid-wrapper"><em>This will be the top-level page in this publication.</em>';
        break;

      default:
        $form['book']['pid']['#description'] = t(
          'The parent page in the publication. The maximum depth for a publication and all child pages is @maxdepth. Some pages in the selected publication may not be available as parents if selecting them would exceed this limit.',
          ['@maxdepth' => $form['book']['parent_depth_limit']['#value']],
        );
        break;
    }
  }
}

/**
 * Implements hook_node_links_alter().
 *
 * If book module has added the "Add child page" link, and we're on a
 * publication type page, alter the link, so it creates a
 * localgov_publication_page, instead of the default book type.
 */
function localgov_publications_node_links_alter(array &$links, NodeInterface $node, array &$context) {

  if (localgov_publications_is_publication_type($node->getType()) && !empty($links['book']['#links']['book_add_child'])) {
    $links['book']['#links']['book_add_child']['url'] = Url::fromRoute('node.add', ['node_type' => 'localgov_publication_page'], ['query' => ['parent' => $node->id()]]);
  }
}
